name: raftkv-bench-3

networks:
  raftnet:
    driver: bridge

volumes:
  wal-node1:
  wal-node2:
  wal-node3:

x-raft-common: &raft-common
  build:
    context: .
    dockerfile: docker/Dockerfile.raftnode
  networks:
    - raftnet
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080/status"]
    interval: 5s
    timeout: 2s
    retries: 3

services:
  raft-bench-3-node-1:
    <<: *raft-common
    container_name: raft-bench-3-node-1
    ports: ["127.0.0.1:18381:8080"]
    environment:
      NODE_ID: raft-bench-3-node-1
      PEERS: "http://raft-bench-3-node-2:8080,http://raft-bench-3-node-3:8080"
      DATA_DIR: /data
    volumes:
      - wal-node1:/data

  raft-bench-3-node-2:
    <<: *raft-common
    container_name: raft-bench-3-node-2
    ports: ["127.0.0.1:18382:8080"]
    environment:
      NODE_ID: raft-bench-3-node-2
      PEERS: "http://raft-bench-3-node-1:8080,http://raft-bench-3-node-3:8080"
      DATA_DIR: /data
    volumes:
      - wal-node2:/data

  raft-bench-3-node-3:
    <<: *raft-common
    container_name: raft-bench-3-node-3
    ports: ["127.0.0.1:18383:8080"]
    environment:
      NODE_ID: raft-bench-3-node-3
      PEERS: "http://raft-bench-3-node-1:8080,http://raft-bench-3-node-2:8080"
      DATA_DIR: /data
    volumes:
      - wal-node3:/data
